# Generated by Django 5.1.15 on 2026-09-23 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_seed_standard_branches'),
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='is_offline',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, db_index=True, default='Manual', max_length=50),
        ),
        migrations.CreateModel(
            name='GoogleSheetConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('spreadsheet_url', models.URLField(max_length=500)),
                ('spreadsheet_id', models.CharField(db_index=True, max_length=150)),
                ('worksheet_name', models.CharField(default='Sheet1', max_length=150)),
                ('assignment_method', models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], default='Automatic', max_length=20)),
                ('field_mapping', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('sync_interval_seconds', models.IntegerField(default=60)),
                ('last_sync_time', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(default='Connected', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='google_sheet_connections', to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='google_sheet_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoogleSheetSyncHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('rows_checked', models.IntegerField(default=0)),
                ('new_leads', models.IntegerField(default=0)),
                ('updated_leads', models.IntegerField(default=0)),
                ('skipped', models.IntegerField(default=0)),
                ('failed', models.IntegerField(default=0)),
                ('status', models.CharField(default='Completed', max_length=50)),
                ('error_summary', models.TextField(blank=True, default='')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_histories', to='leads.googlesheetconnection')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='GoogleSheetRowMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_identifier', models.CharField(db_index=True, max_length=255)),
                ('row_index', models.IntegerField()),
                ('row_data_hash', models.CharField(blank=True, max_length=64)),
                ('source_status', models.CharField(default='Active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row_mappings', to='leads.googlesheetconnection')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheet_mappings', to='leads.lead')),
            ],
            options={
                'ordering': ['row_index'],
                'unique_together': {('connection', 'row_identifier')},
            },
        ),
    ]
