# Generated by Django 5.1.15 on 2026-09-24 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_is_offline_lead_source_googlesheetconnection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('Interested', 'Interested'), ('Follow-up', 'Follow-up'), ('Demo Scheduled', 'Demo Scheduled'), ('Institute Visit', 'Institute Visit'), ('Converted', 'Converted'), ('Lost', 'Lost'), ('Later', 'Later'), ('Discussion', 'Discussion')], default='New', max_length=30),
        ),
    ]
