# Generated by Django 5.1.15 on 2026-09-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_seed_standard_branches'),
        ('leads', '0003_alter_lead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='secondary_branches',
            field=models.ManyToManyField(blank=True, help_text='Additional branches where this lead has appeared', related_name='multi_branch_leads', to='branches.branch'),
        ),
    ]
