# Generated by Django 5.1.15 on 2026-09-26 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_seed_standard_branches'),
        ('leads', '0004_lead_secondary_branches'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadSetupConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_method', models.CharField(choices=[('PERCENTAGE', 'Percentage Based'), ('COUNT', 'Number Of Leads Based')], default='PERCENTAGE', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DuplicateLeadRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('branch_name', models.CharField(blank=True, default='', max_length=150)),
                ('status', models.CharField(blank=True, default='New', max_length=50)),
                ('notes', models.TextField(blank=True, default='Same lead details detected within 10 days.')),
                ('source', models.CharField(default='Google Form', max_length=100)),
                ('data_payload', models.JSONField(blank=True, default=dict)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicate_lead_records', to='branches.branch')),
                ('original_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_records', to='leads.lead')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='GoogleFormConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Google Form Leads', max_length=200)),
                ('form_url', models.CharField(max_length=500)),
                ('form_id', models.CharField(blank=True, db_index=True, default='', max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync_time', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(default='Connected', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='google_form_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelecallerLeadSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_percentage', models.IntegerField(default=0, help_text='e.g. 40 for 40%')),
                ('lead_count', models.IntegerField(default=0, help_text='Target / Limit lead count')),
                ('current_leads_assigned', models.IntegerField(default=0, help_text='Count of leads assigned under this rule')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telecaller_lead_setups', to='branches.branch')),
                ('telecaller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_setup_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['branch__name', 'telecaller__username'],
                'unique_together': {('telecaller', 'branch')},
            },
        ),
    ]
