# Generated by Django 5.1.15 on 2026-09-29 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_leadconnection'),
        ('leads', '0005_leadsetupconfig_duplicateleadrecord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlesheetconnection',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='google_sheet_connections', to='channels.channel'),
        ),
        migrations.AddField(
            model_name='googlesheetconnection',
            name='last_sync_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='googlesheetconnection',
            name='total_leads_imported',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='googlesheetsynchistory',
            name='assigned_leads',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lead',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='assignment_status',
            field=models.CharField(blank=True, db_index=True, default='Assigned', help_text='Status of assignment: Assigned, Pending Assignment, or Unassigned', max_length=50),
        ),
        migrations.AddField(
            model_name='lead',
            name='pending_assignment_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
