# Generated by Django 5.1.15 on 2026-09-30 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_populate_salesheadbranchaccess'),
        ('leads', '0006_googlesheetconnection_channel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='assigned_manager',
            new_name='assigned_sales_head',
        ),
        migrations.AddField(
            model_name='lead',
            name='assigned_branch_head',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'BRANCH_HEAD'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_head_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='assigned_counselor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'COUNSELOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counselor_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='current_owner_type',
            field=models.CharField(choices=[('UNASSIGNED', 'Unassigned'), ('TELECALLER', 'Telecaller'), ('COUNSELOR', 'Counselor'), ('BRANCH_HEAD', 'Branch Head'), ('SALES_HEAD', 'Sales Head'), ('ADMIN', 'Admin')], db_index=True, default='UNASSIGNED', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('Interested', 'Interested'), ('Follow-up', 'Follow-up'), ('Demo Scheduled', 'Demo Scheduled'), ('Institute Visit', 'Institute Visit'), ('Converted', 'Converted'), ('Lost', 'Lost'), ('Later', 'Later'), ('Discussion', 'Discussion'), ('Visit Scheduled', 'Visit Scheduled'), ('Visited', 'Visited'), ('Counseling', 'Counseling'), ('Joined', 'Joined'), ('Not Interested', 'Not Interested'), ('No Answer', 'No Answer'), ('Busy', 'Busy'), ('Not Joined', 'Not Joined')], default='New', max_length=30),
        ),
        migrations.CreateModel(
            name='LeadAssignmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_role', models.CharField(blank=True, default='', max_length=20)),
                ('to_role', models.CharField(blank=True, default='', max_length=20)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='branches.branch')),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_history', to='leads.lead')),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Lead assignment histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, default='', max_length=30)),
                ('new_status', models.CharField(max_length=30)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='leads.lead')),
            ],
            options={
                'verbose_name_plural': 'Lead status histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
