# Generated by Django 5.1.15 on 2026-10-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_backfill_current_owner_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlesheetconnection',
            name='connection_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('DISCONNECTED', 'Disconnected')], db_index=True, default='ACTIVE', max_length=20),
        ),
    ]
