# Generated by Django 5.1.15 on 2026-10-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_googlesheetconnection_connection_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlesheetconnection',
            name='gid',
            field=models.CharField(blank=True, db_index=True, default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('Interested', 'Interested'), ('Follow-up', 'Follow-up'), ('Demo Scheduled', 'Demo Scheduled'), ('Institute Visit', 'Institute Visit'), ('Converted', 'Converted'), ('Lost', 'Lost'), ('Later', 'Later'), ('Discussion', 'Discussion'), ('Visit Scheduled', 'Visit Scheduled'), ('Visited', 'Visited'), ('Counseling', 'Counseling'), ('Joined', 'Joined'), ('Not Interested', 'Not Interested'), ('No Answer', 'No Answer'), ('Busy', 'Busy'), ('Not Joined', 'Not Joined'), ('Historical', 'Historical')], default='New', max_length=30),
        ),
    ]
