# Generated by Django 5.1.15 on 2026-09-21 07:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('call_ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(default=0, help_text='Duration in seconds')),
                ('call_status', models.CharField(choices=[('Initiated', 'Initiated'), ('Connected', 'Connected'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Missed', 'Missed'), ('Cancelled', 'Cancelled')], default='Completed', max_length=20)),
                ('call_outcome', models.CharField(choices=[('Interested', 'Interested'), ('Not Interested', 'Not Interested'), ('Follow-up Required', 'Follow-up Required'), ('Callback Requested', 'Callback Requested'), ('Converted', 'Converted'), ('No Answer', 'No Answer'), ('Busy', 'Busy')], default='Follow-up Required', max_length=30)),
                ('notes', models.TextField(blank=True, default='')),
                ('recording_url', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conducted_calls', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='leads.lead')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_calls', to=settings.AUTH_USER_MODEL)),
                ('telecaller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telecaller_calls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Call histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
