# Generated by Django 5.1.15 on 2026-09-30 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0002_alter_callhistory_caller'),
    ]

    operations = [
        migrations.AddField(
            model_name='callhistory',
            name='notes_completed',
            field=models.BooleanField(db_index=True, default=True, help_text='True if call notes have been submitted and call record is finalized'),
        ),
    ]
