# Generated by Django 5.1.15 on 2026-09-30 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='manager',
        ),
        migrations.AddField(
            model_name='user',
            name='counselor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'COUNSELOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_telecallers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('SALES_HEAD', 'Sales Head'), ('BRANCH_HEAD', 'Branch Head'), ('COUNSELOR', 'Counselor'), ('TELECALLER', 'Telecaller')], default='TELECALLER', help_text='Application access role', max_length=20),
        ),
    ]
