# Generated by Django 5.1.15 on 2026-09-29 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0005_leadsetupconfig_duplicateleadrecord_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriveConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Call Recordings', max_length=200)),
                ('folder_url', models.URLField(max_length=500)),
                ('folder_id', models.CharField(db_index=True, max_length=150)),
                ('connection_status', models.CharField(default='Connected', max_length=50)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drive_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CallRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_file_id', models.CharField(db_index=True, max_length=150, unique=True)),
                ('file_name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(blank=True, default='', max_length=30)),
                ('normalized_mobile_number', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('drive_url', models.URLField(blank=True, default='', max_length=500)),
                ('mime_type', models.CharField(default='audio/mpeg', max_length=50)),
                ('duration', models.CharField(default='04:32', max_length=20)),
                ('recording_date', models.DateTimeField(blank=True, null=True)),
                ('match_status', models.CharField(choices=[('MATCHED', 'Matched'), ('UNMATCHED', 'Unmatched')], db_index=True, default='UNMATCHED', max_length=20)),
                ('unmatched_reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drive_recordings', to='leads.lead')),
                ('drive_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='drive.driveconnection')),
            ],
            options={
                'ordering': ['-recording_date', '-created_at'],
                'indexes': [models.Index(fields=['drive_file_id'], name='drive_callr_drive_f_bcffb5_idx'), models.Index(fields=['normalized_mobile_number'], name='drive_callr_normali_ad66a1_idx'), models.Index(fields=['match_status'], name='drive_callr_match_s_3ab92b_idx')],
            },
        ),
    ]
