# Generated by Django 5.1.15 on 2026-10-04 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='callrecording',
            name='audio_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='callrecording',
            name='file_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='callrecording',
            name='source_folder_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='callrecording',
            name='telecaller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_call_recordings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='driveconnection',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='driveconnection',
            name='is_syncing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driveconnection',
            name='last_error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='driveconnection',
            name='last_sync_status',
            field=models.CharField(default='Success', max_length=50),
        ),
        migrations.AlterField(
            model_name='callrecording',
            name='drive_connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recordings', to='drive.driveconnection'),
        ),
    ]
