# Generated by Django 5.1.15 on 2026-09-25 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_seed_standard_branches'),
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('connection_type', models.CharField(choices=[('Meta', 'Meta / Facebook'), ('Website', 'Website'), ('Google Sheets', 'Google Sheets'), ('WhatsApp', 'WhatsApp'), ('Webhook', 'Custom Webhook'), ('Other', 'Other')], default='Meta', max_length=50)),
                ('status', models.CharField(choices=[('Connected', 'Connected'), ('Disconnected', 'Disconnected'), ('Error', 'Error')], default='Connected', max_length=30)),
                ('page_name', models.CharField(blank=True, default='', max_length=200)),
                ('source_name', models.CharField(default='Meta', max_length=150)),
                ('last_sync_time', models.DateTimeField(blank=True, null=True)),
                ('last_sync_display', models.CharField(blank=True, default='12:58 PM', max_length=50)),
                ('webhook_url', models.CharField(blank=True, default='', max_length=500)),
                ('api_key_or_token', models.CharField(blank=True, default='', max_length=255)),
                ('config_details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_connections', to='branches.branch')),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connections', to='channels.channel')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
