# Generated by Django 5.1.15 on 2026-10-03 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_leadconnection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadconnection',
            name='connection_type',
            field=models.CharField(choices=[('Meta', 'Meta / Facebook'), ('Instagram', 'Instagram'), ('Website', 'Website'), ('Google Sheets', 'Google Sheets'), ('WhatsApp', 'WhatsApp'), ('Webhook', 'Custom Webhook'), ('Other', 'Other')], default='Meta', max_length=50),
        ),
    ]
